trigger:
  branches:
    include:
      - "master"

parameters:
  - name: netbootIP
    type: string
    default: "10.1.30.4"
  - name: netbootUsername
    type: string
    default: "master"
  - name: netbootAssetsDirectory
    type: string
    default: "/home/master/netboot/assets"

pool:
  name: "planet-express-docker-agents"

steps:
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'netb-pronetb001.pem'
- script: |
    echo Installing netb-pronetb001.pem to the trusted CA directory...
    sudo chown root:root $(Agent.TempDirectory)/netb-pronetb001.pem
    sudo chmod a+r $(Agent.TempDirectory)/netb-pronetb001.pem
- task: Docker@2
  inputs:
    containerRegistry: 'DG Modules Container Registry'
    command: 'login'
    addPipelineData: false
- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  inputs:
    rootDirectory: './'
    targetFiles: 'Dockerfile'
    encoding: 'auto'
    writeBOM: true
    actionOnMissing: 'fail'
    keepToken: false
    tokenPrefix: '#{'
    tokenSuffix: '}#'
    useLegacyPattern: false
    enableTelemetry: true
  displayName: 'Replace tokens for Dockerfile'
- script: ./build.sh $(Agent.TempDirectory)/netb-pronetb001.pem ${{ parameters.netbootIP }} ${{ parameters.netbootUsername }} ${{ parameters.netbootAssetsDirectory }}
  displayName: "Build caching squashfs"
