version: "3"
services:
  netboot-http:
    image: nginx:stable-alpine
    container_name: netboot-http
    # This corresponds to the `master` user on the caching server
    user: 1000:1000
    volumes:
      - /home/master/nginx.conf:/etc/nginx/nginx.conf
      - /home/master/netboot/assets:/assets
    ports:
      - 80:80
    restart: unless-stopped
